---
# tasks file for programming-langs

- name: Install Ruby packages
  apt:
    name: "{{ ruby_packages }}"
    state: latest

- name: Install Haskell packages
  apt:
    name: "{{ haskell_packages }}"
    state: latest

- name: Install Prolog packages
  apt:
    name: "{{ prolog_packages }}"
    state: latest
