---
# tasks file for robot-pkgs
- name: Add ROS repository
  apt_repository:
    repo: deb http://packages.ros.org/ros/ubuntu xenial main
    filename: 'ros-latest'
    state: present
- name: Add ROS key
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: 421C365BD9FF1F717815A3895523BAEEB01FA116
    state: present
- name: Update apt cache
  apt:
    update_cache: yes
- name: Install robot development packages
  apt: name={{ item }} state=present
  with_items:
    - ros-kinetic-desktop-full
    - gazebo7
    - rviz
# Dest becomes path in Ansible 2.3+
- name: Create ROS profile entries
  blockinfile:
    dest: '{{ global_profile_path }}'
    marker: "## {mark} ROS profile entries ##"
    block: |
      source /opt/ros/kinetic/setup.bash
      export TURTLEBOT_3D_SENSOR=kinect
  notify:
  - Suggest restart
- name: Init rosdep if missing
  command: rosdep init
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
- name: Update rosdep for each user
  command: rosdep update
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ real_users }}"
- name: Create Catkin workspace directory
  file:
    path: '{{ item.homedir }}/catkin_ws/src/'
    state: directory
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
  with_items: "{{ real_users }}"
- name: Init Catkin workspace
  shell: source /opt/ros/kinetic/setup.bash && catkin_make
  args:
    executable: /bin/bash
    chdir: '{{ item.homedir }}/catkin_ws/'
  become: yes
  become_user: "{{ item.user }}"
  with_items: "{{ real_users }}"
