---
# tasks file for wireless-printing
- name: Install printer packages
  apt: name={{ item }} state=latest
  loop:
    - cups
    - cups-client
# The service must be running for lpadmin commands to work
# and the server must be working to print
- name: Ensure CUPS is started
  service:
      name: cups
      enabled: yes
      state: started
# Do not indent continuation lines of a multi-line block,
# they become newlines when parsed
- name: Add printers
  shell: >
    lpstat -p "{{ item.name }}" ||
    lpadmin -p "{{ item.name }}" -E
    -v "{{ item.queue }}"
    -L "{{ item.descr }}"
    -m "drv:///sample.drv/generic.ppd"
    -o "Duplex=DuplexNoTumble"
    -o "Option1=True"
    -o "printer-is-shared=false"
  register: lpstat_result
  changed_when: '"Invalid destination name" in lpstat_result.stderr'
  with_items: "{{ printers }}"
