---
galaxy_info:
  author: Unix Users Group
  description: Installs the Eclipse IDE
  company: James Madison University
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  galaxy_tags: []
  # List tags for your role here, one per line. A tag is a keyword that
  # describes and categorizes the role. Users find roles by searching for tags.
  # Be sure to remove the '[]' above, if you add tags to this list.
  #
  # NOTE: A tag is limited to a single word comprised of alphanumeric
  # characters. Maximum 20 tags per role.
dependencies: []
# TODO Add user as a dependency
