---
# vars file for robot-pkgs

# Keep UMD first to prefer downloads from there
ros_repos:
  - deb http://mirror.umd.edu/packages.ros.org/ros/ubuntu xenial main
  - deb http://packages.ros.org/ros/ubuntu xenial main

ros_packages:
    - ros-melodic-desktop-full
    - gazebo9
    - rviz
    - g++

usb_warning_msg: |
    "<b>USB Contollers missing</b>
    In order to effectively connect robots to the VM
    ECHI/xHCI controllers need to be installed from
    VirtualBox. See <a href='https://jmunixusers.github.io/presentations/virtualbox-extension-pack.html'>these instructions</a> for
    more information on how to install them"

