---
# vars file for wireless-printing
# Printer attributes must be at the same indentation level
printers:
  - bandw:
    name: JMU-LabPrintBW
    queue: lpd://labprintremote@labprint.jmu.edu/LabPrintBW
    descr: JMU Labs & Libraries
    driver: drv:///sample.drv/generic.ppd
  - color:
    name: JMU-LabPrintColor
    queue: lpd://labprintremote@labprint.jmu.edu/LabPrintColor
    descr: JMU Labs & Libraries
    driver: drv:///sample.drv/generic.ppd

wireless_printing_packages:
  - cups
  - cups-client
