---
# vars file for oem
oem_base_path: /opt

packages_to_install:
    - zenity

# https://github.com/jmunixusers/cs-vm-build/issues/11#issuecomment-347015788 
packages_to_remove:
    - bluez*
    - btrfs-tools
    - fonts*gujr*
    - fonts*guru*
    - fonts-beng*
    - fonts-deva*
    - fonts-gargi*
    - fonts-gubbi
    - fonts-gujr*
    - fonts-guru*
    - fonts-kacst*
    - fonts-kalapi
    - fonts-khmeros-core
    - fonts-lao
    - fonts-lklug-sinhala
    - fonts-lohit-*
    - fonts-nakula
    - fonts-nanum
    - fonts-navilu
    - fonts-noto-cjk
    - fonts-orya-extra
    - fonts-pagul
    - fonts-sahadeva
    - fonts-samyak-*
    - fonts-sarai
    - fonts-sil-*
    - fonts-smc
    - fonts-takao-pgothic
    - fonts-telu-extra
    - fonts-tibetan-machine
    - fonts-tlwg-*
    - fonts-wqy-microhei
    - gimp*
    - hexchat*
    - hunspell-de-at
    - hunspell-de-ch
    - hunspell-de-de
    - hunspell-en-ca
    - hunspell-en-gb
    - hunspell-en-za
    - hunspell-fr
    - hunspell-fr-classical
    - hunspell-it
    - hunspell-ru
    - hypgen-fr
    - hyphen-de
    - hyphen-it
    - hyphen-ru
    - libllvm3.8
    - libreoffice-common
    - mint-artwork-mate
    - mint-backgrounds-sarah
    - mint-backgrounds-serena
    - mint-backgrounds-sonya
    - mono-*
    - myspell-en-au
    - myspell-en-gb
    - myspell-en-za
    - myspell-es
    - myspell-it
    - myspell-pt*
    - mythes-de
    - mythes-de-ch
    - mythes-en-au
    - mythes-fr
    - mythes-it
    - mythes-pt-pt
    - mythes-ru
    - openvpn
    - pidgin*
    - pix*
    - rhythmbox*
    - simple-scan
    - thunderbird*
    - tomboy
    - transmission*
    - vlc*
    - wbritish
    - xplayer*
    - xscreensaver-*
