---
# vars file for oem
packages_to_install:
  - zenity

upgrade_pre_mintupdate:
  - mintupdate
  - mint-upgrade-info

skel_path: "/etc/skel"
skel_desktop_file_path: "{{ skel_path }}/Desktop"

# https://github.com/jmunixusers/cs-vm-build/issues/11#issuecomment-347015788
packages_to_remove:
  - bluez*
  - btrfs-tools
  - fonts*gujr*
  - fonts*guru*
  - fonts-beng*
  - fonts-deva*
  - fonts-gargi*
  - fonts-gubbi
  - fonts-gujr*
  - fonts-guru*
  - fonts-kacst*
  - fonts-kalapi
  - fonts-khmeros-core
  - fonts-lao
  - fonts-lklug-sinhala
  - fonts-lohit-*
  - fonts-nakula
  - fonts-nanum
  - fonts-navilu
  - fonts-noto*
  - fonts-orya-extra
  - fonts-pagul
  - fonts-sahadeva
  - fonts-samyak-*
  - fonts-sarai
  - fonts-sil-*
  - fonts-smc-*
  - fonts-takao-pgothic
  - fonts-telu-extra
  - fonts-tibetan-machine
  - fonts-tlwg-*
  - fonts-wqy-microhei
  - hexchat*
  - hunspell-de-*
  - hunspell-en-au
  - hunspell-en-ca
  - hunspell-en-gb
  - hunspell-en-za
  - hunspell-es
  - hunspell-fr*
  - hunspell-it
  - hunspell-pt*
  - hunspell-ru
  - hyphen-de
  - hyphen-en-ca
  - hyphen-en-gb
  - hyphen-fr
  - hyphen-it
  - hyphen-pt*
  - hyphen-ru
  - libreoffice*
  - linux*oem
  - mint-artwork-mate
  - mint-backgrounds-sarah
  - mint-backgrounds-serena
  - mint-backgrounds-sonya
  - mint-backgrounds-tara
  - mint-backgrounds-tessa
  - mint-backgrounds-tina
  - mono-*
  - myspell-*
  - mythes-de
  - mythes-de-ch
  - mythes-en-au
  - mythes-fr
  - mythes-it
  - mythes-pt-pt
  - mythes-ru
  - openvpn
  - pidgin*
  - pix*
  - rhythmbox*
  - simple-scan
  - timeshift
  - thunderbird*
  - tomboy
  - transmission*
  - vlc*
  - wbritish
  - xscreensaver-*
