---
# tasks file for basic-prog-pkgs
- name: Install introductory development packages
  apt: name={{ item }} state=present
  with_items:
    - artha
    - bless
    - geany
    - idle
    - meld
    - pinta
    - python-pygame
    - wireshark
    - fonts-crosextra-caladea
    - fonts-crosextra-carlito
    - libreoffice
    - libreoffice-templates
    - libreoffice-style-tango
    - logisim
- name: Copy idlerc prefs
  copy:
    src: .idlerc
    dest: '{{ item.homedir }}'
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
    directory_mode: 0750
    mode: 0640
  with_items: "{{ real_users }}"
- name: Copy lab worksheet
  copy:
    src: Lab04-Worksheet.txt
    dest: '{{ item.homedir }}'
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
    mode: 0640
  with_items: "{{ real_users }}"
- name: Copy mimeapps Idle pref
  copy:
    src: mimeapps.list
    dest: '{{ item.homedir }}/.config/'
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
    mode: 0640
    force: no
  with_items: "{{ real_users }}"
# Dest becomes path in Ansible 2.3+
- name: Set Idle pref in existing mimeapps
  lineinfile: 
    dest: '{{ item.homedir }}/.config/mimeapps.list'
    regexp: '^text/x-python='
    line: 'text/x-python=idle-python2.7.desktop;gedit.desktop;pluma.desktop'
  with_items: "{{ real_users }}"
